// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Uploaded_Files : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Uploaded_Files));
        
        string IMigrationMetadata.Id
        {
            get { return "202311272038514_Uploaded_Files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
