// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Conversion_Histories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conversion_Histories));
        
        string IMigrationMetadata.Id
        {
            get { return "202311272133452_Conversion_Histories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
